name: Run tests

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node: [14.x, 12.x, 10.x]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: npm install and test
      run: |
        npm ci
        npm test
    - name: Checkout gohugoio/hugoBasicExample
      uses: actions/checkout@master
      with:
        repository: gohugoio/hugoBasicExample
        path: site/
        fetch-depth: 1
    - name: Build example site
      run: node cli.js --source site/ --minify --verbose
