name: Run tests

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node: [13.x, 12.x, 10.x]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: npm install and test
      run: |
        npm ci
        npm test
      env:
        CI: true
    - name: Checkout gohugoio/hugoDocs
      uses: actions/checkout@master
      with:
        repository: gohugoio/hugoDocs
        path: docs/
        fetch-depth: 1
    - name: Build docs site
      run: node cli.js --source docs/ --minify --verbose
