name: Run tests

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        node:
        - 16
        - 14
        - 12
        - 10
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: npm install and test
      run: |
        npm ci
        npm audit
        npm test
    - name: Checkout gohugoio/hugoBasicExample
      uses: actions/checkout@master
      with:
        repository: gohugoio/hugoBasicExample
        path: site/
        fetch-depth: 1
    - name: Build example site
      run: node cli.js --source site/ --minify --verbose
